import os
env = Environment(
    CPPPATH = ['F:/project/CPP/xulun', '.'],
    CFLAGS = '-g',
)
#Program("main.c")
#env.Program(['进制转换.c','SequenceStack.c'])
#env.Program(['LineEdit.c','SequenceStack.c'])
env.Program(['Maze_main.c','Maze.c','SequenceStack.c'])